DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS
(
  USERNAME VARCHAR(50) PRIMARY KEY,
  PASSWORD VARCHAR(64) NOT NULL
);

INSERT INTO USERS (USERNAME, PASSWORD) VALUES
  ('ADMIN', '$2a$10$AIMLSB/ryyjzdBqB5gMDCeUPk4oyR0nQJIMYRIeAKh6snMFalx6FG'), -- PASS: 'ADMIN'
  ('DEMO_USER', '$2a$08$ZLxHsMGAFwPSw1VhIfCBfej2I84KkuPPNzx/Q/6Q3Enk5fm/Zoqzq'),   -- PASS: ''
  ('DEMO_MASTER', '$2a$08$ZLxHsMGAFwPSw1VhIfCBfej2I84KkuPPNzx/Q/6Q3Enk5fm/Zoqzq'); -- PASS: ''